/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUsernameRouteRouteImport } from './routes/users/$username/route'
import { Route as UsersUsernameIndexRouteImport } from './routes/users/$username/index'
import { Route as UsersUsernameWorldRouteImport } from './routes/users/$username/world'
import { Route as UsersUsernameReposOwnerRepoIndexRouteImport } from './routes/users/$username/repos/$owner/$repo/index'
import { Route as UsersUsernameReposOwnerRepoCommitsShaRouteImport } from './routes/users/$username/repos/$owner/$repo/commits/$sha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRouteRoute = UsersUsernameRouteRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameIndexRoute = UsersUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUsernameRouteRoute,
} as any)
const UsersUsernameWorldRoute = UsersUsernameWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => UsersUsernameRouteRoute,
} as any)
const UsersUsernameReposOwnerRepoIndexRoute =
  UsersUsernameReposOwnerRepoIndexRouteImport.update({
    id: '/repos/$owner/$repo/',
    path: '/repos/$owner/$repo/',
    getParentRoute: () => UsersUsernameRouteRoute,
  } as any)
const UsersUsernameReposOwnerRepoCommitsShaRoute =
  UsersUsernameReposOwnerRepoCommitsShaRouteImport.update({
    id: '/repos/$owner/$repo/commits/$sha',
    path: '/repos/$owner/$repo/commits/$sha',
    getParentRoute: () => UsersUsernameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users/$username': typeof UsersUsernameRouteRouteWithChildren
  '/users/$username/world': typeof UsersUsernameWorldRoute
  '/users/$username/': typeof UsersUsernameIndexRoute
  '/users/$username/repos/$owner/$repo/': typeof UsersUsernameReposOwnerRepoIndexRoute
  '/users/$username/repos/$owner/$repo/commits/$sha': typeof UsersUsernameReposOwnerRepoCommitsShaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users/$username/world': typeof UsersUsernameWorldRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/users/$username/repos/$owner/$repo': typeof UsersUsernameReposOwnerRepoIndexRoute
  '/users/$username/repos/$owner/$repo/commits/$sha': typeof UsersUsernameReposOwnerRepoCommitsShaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users/$username': typeof UsersUsernameRouteRouteWithChildren
  '/users/$username/world': typeof UsersUsernameWorldRoute
  '/users/$username/': typeof UsersUsernameIndexRoute
  '/users/$username/repos/$owner/$repo/': typeof UsersUsernameReposOwnerRepoIndexRoute
  '/users/$username/repos/$owner/$repo/commits/$sha': typeof UsersUsernameReposOwnerRepoCommitsShaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users/$username'
    | '/users/$username/world'
    | '/users/$username/'
    | '/users/$username/repos/$owner/$repo/'
    | '/users/$username/repos/$owner/$repo/commits/$sha'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users/$username/world'
    | '/users/$username'
    | '/users/$username/repos/$owner/$repo'
    | '/users/$username/repos/$owner/$repo/commits/$sha'
  id:
    | '__root__'
    | '/'
    | '/users/$username'
    | '/users/$username/world'
    | '/users/$username/'
    | '/users/$username/repos/$owner/$repo/'
    | '/users/$username/repos/$owner/$repo/commits/$sha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersUsernameRouteRoute: typeof UsersUsernameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username': {
      id: '/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/': {
      id: '/users/$username/'
      path: '/'
      fullPath: '/users/$username/'
      preLoaderRoute: typeof UsersUsernameIndexRouteImport
      parentRoute: typeof UsersUsernameRouteRoute
    }
    '/users/$username/world': {
      id: '/users/$username/world'
      path: '/world'
      fullPath: '/users/$username/world'
      preLoaderRoute: typeof UsersUsernameWorldRouteImport
      parentRoute: typeof UsersUsernameRouteRoute
    }
    '/users/$username/repos/$owner/$repo/': {
      id: '/users/$username/repos/$owner/$repo/'
      path: '/repos/$owner/$repo'
      fullPath: '/users/$username/repos/$owner/$repo/'
      preLoaderRoute: typeof UsersUsernameReposOwnerRepoIndexRouteImport
      parentRoute: typeof UsersUsernameRouteRoute
    }
    '/users/$username/repos/$owner/$repo/commits/$sha': {
      id: '/users/$username/repos/$owner/$repo/commits/$sha'
      path: '/repos/$owner/$repo/commits/$sha'
      fullPath: '/users/$username/repos/$owner/$repo/commits/$sha'
      preLoaderRoute: typeof UsersUsernameReposOwnerRepoCommitsShaRouteImport
      parentRoute: typeof UsersUsernameRouteRoute
    }
  }
}

interface UsersUsernameRouteRouteChildren {
  UsersUsernameWorldRoute: typeof UsersUsernameWorldRoute
  UsersUsernameIndexRoute: typeof UsersUsernameIndexRoute
  UsersUsernameReposOwnerRepoIndexRoute: typeof UsersUsernameReposOwnerRepoIndexRoute
  UsersUsernameReposOwnerRepoCommitsShaRoute: typeof UsersUsernameReposOwnerRepoCommitsShaRoute
}

const UsersUsernameRouteRouteChildren: UsersUsernameRouteRouteChildren = {
  UsersUsernameWorldRoute: UsersUsernameWorldRoute,
  UsersUsernameIndexRoute: UsersUsernameIndexRoute,
  UsersUsernameReposOwnerRepoIndexRoute: UsersUsernameReposOwnerRepoIndexRoute,
  UsersUsernameReposOwnerRepoCommitsShaRoute:
    UsersUsernameReposOwnerRepoCommitsShaRoute,
}

const UsersUsernameRouteRouteWithChildren =
  UsersUsernameRouteRoute._addFileChildren(UsersUsernameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersUsernameRouteRoute: UsersUsernameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
